[package]
name = "service-gateway"
version = "0.1.0"
edition = "2021"
authors = ["arkSong <arksong2018@gmail.com>"]
description = "API Gateway for RWA platform microservices"

[dependencies]
actix-web = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
jsonwebtoken = { workspace = true }
async-trait = { workspace = true }
core-utils = { path = "../core-utils" }
core-security = { path = "../core-security" }
futures-util = "0.3"
rand = "0.8"
prometheus = "0.13"

[dev-dependencies]
tokio-test = "0.4"
