# =====================================================================================
# RWA Tokenization Platform - Custody Service
# 
# Author: arkSong (arksong2018@gmail.com)
# =====================================================================================

[package]
name = "service-custody"
version = "0.1.0"
edition = "2021"
authors = ["arkSong <arksong2018@gmail.com>"]
description = "Enterprise-grade custody service for RWA tokenization platform"
license = "MIT"
repository = "https://github.com/rwa-platform/service-custody"

[dependencies]
# Web framework
axum = { version = "0.7", features = ["macros"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }
hyper = { version = "1.0", features = ["full"] }

# Async runtime
tokio = { version = "1.35", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# HTTP client
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "rust_decimal"] }

# Cache
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }

# Decimal arithmetic
rust_decimal = { version = "1.33", features = ["serde-with-str"] }
rust_decimal_macros = "1.33"

# Date and time
chrono = { version = "0.4", features = ["serde"] }

# UUID
uuid = { version = "1.6", features = ["v4", "serde"] }

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-actix-web = "0.7"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Configuration
config = "0.14"

# Metrics
prometheus = "0.13"

# Security and cryptography
jsonwebtoken = "9.2"
aes-gcm = "0.10"
rand = "0.8"
sha2 = "0.10"
ed25519-dalek = "2.0"
secp256k1 = "0.28"
hmac = "0.12"
subtle = "2.5"

# Blockchain integrations
ethers = { version = "2.0", features = ["rustls", "ws"] }
bitcoin = "0.31"
# solana-client = "1.17" # Commented out due to version conflicts
# solana-sdk = "1.17" # Commented out due to version conflicts

# Hardware Security Module (HSM) support
# pkcs11 = { version = "0.5", optional = true } # Commented out due to version conflicts

# Multi-signature support
threshold_crypto = { version = "0.4", optional = true }

# Utilities
once_cell = "1.19"
hex = "0.4"
base64 = "0.21"
regex = "1.10"
url = "2.4"

[dev-dependencies]
axum-test = "14.0"
tokio-test = "0.4"
tempfile = "3.8"

[features]
default = ["threshold"]
# hsm = ["pkcs11"] # Commented out due to dependency issues
threshold = ["threshold_crypto"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[[bin]]
name = "service-custody"
path = "src/main.rs"
