# =====================================================================================
# File: rustfmt.toml
# Description: Enterprise-grade Rustfmt configuration for StableRWA Platform
# Author: arkSong (arksong2018@gmail.com)
# Framework: StableRWA - Enterprise RWA Tokenization Technology Framework Platform
# =====================================================================================

# Edition and version
edition = "2021"
version = "Two"

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
imports_granularity = "Crate"
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Functions and methods
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
indent_style = "Block"

# Expressions and statements
binop_separator = "Front"
combine_control_expr = true
condense_wildcard_suffixes = false
force_explicit_abi = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = false
hex_literal_case = "Preserve"

# Comments and documentation
comment_width = 80
doc_comment_code_block_width = 100
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# Whitespace and newlines
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
empty_item_single_line = true
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
newline_style = "Unix"
remove_nested_parens = true
spaces_around_ranges = false
struct_field_align_threshold = 0
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = false
use_try_shorthand = false

# Advanced formatting
chain_width = 60
single_line_if_else_max_width = 50
struct_lit_single_line = true
where_single_line = false

# Unstable features (requires nightly)
# These are commented out for stable compatibility
# unstable_features = true
# format_generated_files = false
# skip_children = false
# hide_parse_errors = false
# error_on_line_overflow = false
# error_on_unformatted = false
# report_todo = "Never"
# report_fixme = "Never"
# ignore = []

# Enterprise-specific settings
merge_derives = true
use_small_heuristics = "Default"
short_array_element_width_threshold = 10
array_width = 60
attr_fn_like_width = 70
chain_width = 60
fn_call_width = 60
single_line_if_else_max_width = 50
struct_lit_width = 18
struct_variant_width = 35
where_single_line = false

# Macro formatting
macro_block_end = "MacroDefault"
overflow_delimited_expr = false

# Module and item organization
reorder_impl_items = true
type_punctuation_density = "Wide"

# String formatting
format_strings = false
format_macro_bodies = true

# Miscellaneous
edition = "2021"
force_explicit_abi = true
format_generated_files = true
