[package]
name = "testing-utils"
version = "0.1.0"
edition = "2021"
authors = ["arkSong <arksong2018@gmail.com>"]
description = "Testing utilities and frameworks for StableRWA platform"
license = "MIT"

[dependencies]
# Async runtime
tokio = { version = "1.0", features = ["full"] }
tokio-test = "0.4"

# Testing frameworks
mockall = "0.11"
proptest = "1.4"
fake = { version = "2.10", features = ["derive", "chrono", "uuid"] }
wiremock = "0.5"

# Test containers
testcontainers = "0.15"
testcontainers-modules = { version = "0.3", features = ["postgres", "redis"] }

# Serialization for test data
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# Date and time
chrono = { version = "0.4", features = ["serde"] }

# UUID generation
uuid = { version = "1.0", features = ["v4", "serde"] }

# HTTP client for API testing
reqwest = { version = "0.11", features = ["json"] }

# Database testing
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }

# Logging for tests
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-test = "0.2"

# Assertions
assert_matches = "1.5"
pretty_assertions = "1.4"

# Decimal arithmetic
rust_decimal = { version = "1.0", features = ["serde-json"] }

# Temporary files and directories
tempfile = "3.8"

# Environment variables
dotenvy = "0.15"

# Random data generation
rand = "0.8"

# Internal dependencies for testing
core-utils = { path = "../core-utils" }
core-security = { path = "../core-security" }
core-blockchain = { path = "../core-blockchain" }
core-compliance = { path = "../core-compliance" }
core-asset-lifecycle = { path = "../core-asset-lifecycle" }
core-risk-management = { path = "../core-risk-management" }
core-bridge = { path = "../core-bridge" }
core-did = { path = "../core-did" }
core-analytics = { path = "../core-analytics" }
core-trading = { path = "../core-trading" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "test_performance"
harness = false
