global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@rwa-platform.com'
  smtp_auth_username: 'alerts@rwa-platform.com'
  smtp_auth_password: 'your-email-password'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alert routing
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    # Critical alerts go to on-call team immediately
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m

    # Database alerts go to DBA team
    - match_re:
        alertname: ^(PostgreSQL|Redis).*
      receiver: 'database-team'

    # Security alerts go to security team
    - match_re:
        alertname: ^(HighFailedAuthentication|SuspiciousAPI).*
      receiver: 'security-team'

    # Business logic alerts go to product team
    - match_re:
        alertname: ^(HighAssetTokenization|AIService).*
      receiver: 'product-team'

    # Infrastructure alerts go to DevOps team
    - match_re:
        alertname: ^(HighCPU|HighMemory|ServiceDown).*
      receiver: 'devops-team'

# Inhibition rules to suppress redundant alerts
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '^(HighErrorRate|HighResponseTime)$'
    equal: ['instance']

# Receivers define how to send notifications
receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'devops@rwa-platform.com'
        subject: '[RWA Platform] Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@rwa-platform.com'
        subject: '[CRITICAL] RWA Platform Alert: {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#critical-alerts'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
    pagerduty_configs:
      - routing_key: 'your-pagerduty-integration-key'
        description: '{{ .GroupLabels.alertname }}: {{ .GroupLabels.instance }}'

  - name: 'database-team'
    email_configs:
      - to: 'dba@rwa-platform.com'
        subject: '[Database] RWA Platform Alert: {{ .GroupLabels.alertname }}'
        body: |
          Database Alert Detected
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.instance }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#database-alerts'
        title: '🗄️ Database Alert: {{ .GroupLabels.alertname }}'

  - name: 'security-team'
    email_configs:
      - to: 'security@rwa-platform.com'
        subject: '[Security] RWA Platform Alert: {{ .GroupLabels.alertname }}'
        body: |
          🔒 Security Alert Detected
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#security-alerts'
        title: '🔒 Security Alert: {{ .GroupLabels.alertname }}'

  - name: 'product-team'
    email_configs:
      - to: 'product@rwa-platform.com'
        subject: '[Product] RWA Platform Alert: {{ .GroupLabels.alertname }}'
        body: |
          Product/Business Logic Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.job }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#product-alerts'
        title: '📊 Product Alert: {{ .GroupLabels.alertname }}'

  - name: 'devops-team'
    email_configs:
      - to: 'devops@rwa-platform.com'
        subject: '[Infrastructure] RWA Platform Alert: {{ .GroupLabels.alertname }}'
        body: |
          Infrastructure Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#devops-alerts'
        title: '⚙️ Infrastructure Alert: {{ .GroupLabels.alertname }}'

# Webhook configurations for custom integrations
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://service-gateway:8080/webhooks/alerts'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'webhook-user'
            password: 'webhook-password'
