# =====================================================================================
# Kubernetes Secrets and ConfigMaps for RWA Platform Project
# Stores TLS certs, API keys, and environment configs
# Author: arkSong (arksong2018@gmail.com)
# =====================================================================================

# TLS Secret (replace with your real cert and key)
apiVersion: v1
kind: Secret
metadata:
  name: rwa-tls-secret
  namespace: rwa-platform
  labels:
    app: webui
  annotations:
    kubernetes.io/tls-acme: "true"
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>
---
# API Key Secret (example for backend services)
apiVersion: v1
kind: Secret
metadata:
  name: rwa-api-key
  namespace: rwa-platform
type: Opaque
data:
  API_KEY: <base64-encoded-api-key>
---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: rwa-config
  namespace: rwa-platform
data:
  RUST_LOG: info
  NODE_ENV: production
  # Add more environment variables as needed 