[package]
name = "service-asset"
version = "0.1.0"
edition = "2021"
authors = ["arkSong <arksong2018@gmail.com>"]
description = "Production-grade asset management service for RWA platform"

[dependencies]
# Core dependencies
actix-web = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }

# Database
sqlx = { workspace = true }
rust_decimal = { workspace = true }

# Internal dependencies
core-utils = { path = "../core-utils" }
core-security = { path = "../core-security" }
core-blockchain = { path = "../core-blockchain" }
core-asset-lifecycle = { path = "../core-asset-lifecycle" }
core-compliance = { path = "../core-compliance" }
core-risk-management = { path = "../core-risk-management" }

# External blockchain
ethers = { workspace = true, features = ["rustls"] }

# HTTP client
reqwest = { workspace = true }

# Validation
validator = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
