[package]
name = "service-asset"
version = "0.1.0"
edition = "2021"
authors = ["arkSong <arksong2018@gmail.com>"]
description = "Production-grade asset management service for RWA platform"

[dependencies]
# Core dependencies
actix-web = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }

# Database
sqlx = { workspace = true }
rust_decimal = { workspace = true, features = ["db-postgres"] }

# Internal dependencies (temporarily disabled due to compilation issues)
# core-utils = { path = "../core-utils" }
# core-security = { path = "../core-security" }
# core-blockchain = { path = "../core-blockchain" }
# core-asset-lifecycle = { path = "../core-asset-lifecycle" }
# core-compliance = { path = "../core-compliance" }
# core-risk-management = { path = "../core-risk-management" }

# External blockchain
ethers = { workspace = true, features = ["rustls"] }

# HTTP client
reqwest = { workspace = true }

# Validation
validator = { workspace = true }

# Metrics and monitoring
prometheus = "0.13"
futures-util = "0.3"

# Caching
redis = { version = "0.24", features = ["aio", "tokio-comp"] }
bincode = "1.3"
flate2 = "1.0"

# Configuration
toml = "0.8"

# Additional utilities
hex = "0.4"
num_cpus = "1.16"
tracing-subscriber = { version = "0.3", features = ["json"] }

# Async runtime
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
tokio-test = "0.4"
