[package]
name = "user-service"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
log = "0.4"
polkadot-integration = { path = "../polkadot-integration" }
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
env_logger = "0.11.8"
