# =====================================================================================
# RWA Tokenization Platform - Risk Management Service
# 
# Author: arkSong (arksong2018@gmail.com)
# =====================================================================================

[package]
name = "service-risk"
version = "0.1.0"
edition = "2021"
authors = ["arkSong <arksong2018@gmail.com>"]
description = "Enterprise-grade risk management service for RWA tokenization platform"
license = "MIT"
repository = "https://github.com/rwa-platform/service-risk"

[dependencies]
# Web framework
actix-web = "4.4"
actix-cors = "0.7"

# Async runtime
tokio = { version = "1.35", features = ["full"] }
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# HTTP client
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "decimal"] }

# Cache
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }

# Decimal arithmetic
rust_decimal = { version = "1.33", features = ["serde-with-str"] }
rust_decimal_macros = "1.33"

# Date and time
chrono = { version = "0.4", features = ["serde"] }

# UUID
uuid = { version = "1.6", features = ["v4", "serde"] }

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-actix-web = "0.7"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Configuration
config = "0.14"

# Metrics
prometheus = "0.13"

# Security
jsonwebtoken = "9.2"

# Mathematical computations
nalgebra = "0.32"
statrs = "0.16"

# Machine learning for risk modeling
candle-core = { version = "0.3", optional = true }
candle-nn = { version = "0.3", optional = true }
candle-transformers = { version = "0.3", optional = true }

# Time series analysis
polars = { version = "0.35", features = ["lazy", "temporal", "strings"] }

# Utilities
once_cell = "1.19"

[dev-dependencies]
actix-web-test = "4.4"
tempfile = "3.8"
approx = "0.5"

[features]
default = ["ml"]
ml = ["candle-core", "candle-nn", "candle-transformers"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[[bin]]
name = "service-risk"
path = "src/main.rs"
